### PR TITLE
72.1

### PR DESCRIPTION
**Pull request by DerThorsten**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xhochy** [comment]
@DerThorsten Happy to have this PR. Any reason why you closed it again?

**Comment by DerThorsten** [comment]
I will reopen this later today....was a bit to quick with the SHA256 checksums.

**Comment by DerThorsten** [comment]
@xhochy  no idea how to tackle the linux fail
```cpp
writesrc.cpp:202:35: error: 'PRId64' was not declared in this scope
  202 |         fprintf(f, value<=9 ? "%" PRId64 : "0x%" PRIx64, value);
```

**Comment by minrk** [comment]
@conda-forge-admin please rerender

**Comment by minrk** [comment]
The PRId64 errors were fixed upstream by https://github.com/unicode-org/icu/pull/2239 and https://github.com/unicode-org/icu/pull/2250 , I've added the patch from those PRs.

**Review by ocefpaf — APPROVED** [review]

**Comment by minrk** [comment]
@xhochy yeah, I [tracked it down](https://github.com/conda/conda-build/issues/4810#issuecomment-1475968814) to a lack of pinning of cctools, where cctools is installed with libllvm15, which has the transitive dependency on libxml2 -> icu. I don't know how to force cctools to match libllvm version. Maybe the cctools and clangdev repos need to be updated to ensure these are kept in sync?

**Comment by h-vetinari** [comment]
We've been getting more consistent in building llvm with its support libraries for various formats (libxml2, zlib, zstd) ever since LLVM 14, but accelerating with LLVM 15 and now hopefully converging to a steady state with LLVM 16.

zlib/zstd come without external dependencies, so this has a very small blast radius, but libxml2 (additionally) depends on `icu` / `libiconv` / `xz`. That means these libs are now dependencies of the compilers stack on osx, and as such will need to use the bootstrap compilers (which come without any dependencies, exactly to deal with this scenario).

If this turns out to be too burdensome for the feedstocks involved, we can discuss removing libxml2-support in llvmdev/clangdev etc.

**Comment by h-vetinari** [comment]
I guess we could add a runconstraint to `cctools_{{ cross_platform }}` on `libllvm<maj>`, that should always be correct.

**Comment by minrk** [comment]
It's not cctools' pin of libllvm that's the problem, it's clang_osx-64's pin _of_ cctools, which only depends on `cctools` (no pin). And since libllvm15 doesn't conflict with libllvm14, the cctools with libllvm15 is still a valid solution to clang_osx-64=14's dependency on cctools. I _think_ it should to depend on `cctools _with_ libllvm14`, but that's not currently pinnable via the build string or other mutex package, and I don't know enough about the relationships of these packages to be sure about that.

For example:

<details>
<summary>

```
/conda-x86/bin/conda create -n clang clangxx_osx-64=14 cctools_osx-64=973.0.1=h48a5a9d_12
```

</summary>

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/minrk/conda-x86/envs/clang

  added / updated specs:
    - cctools_osx-64==973.0.1=h48a5a9d_12
    - clangxx_osx-64=14


The following NEW packages will be INSTALLED:

  ca-certificates    conda-forge/osx-64::ca-certificates-2022.12.7-h033912b_0
  cctools_osx-64     conda-forge/osx-64::cctools_osx-64-973.0.1-h48a5a9d_12
  clang              conda-forge/osx-64::clang-14.0.6-h694c41f_0
  clang-14           conda-forge/osx-64::clang-14-14.0.6-default_h55ffa42_0
  clang_osx-64       conda-forge/osx-64::clang_osx-64-14.0.6-h3113cd8_5
  clangxx            conda-forge/osx-64::clangxx-14.0.6-default_h55ffa42_0
  clangxx_osx-64     conda-forge/osx-64::clangxx_osx-64-14.0.6-h6f97653_5
  compiler-rt        conda-forge/osx-64::compiler-rt-14.0.6-h613da45_0
  compiler-rt_osx-64 conda-forge/noarch::compiler-rt_osx-64-14.0.6-hab78ec2_0
  icu                conda-forge/osx-64::icu-70.1-h96cf925_0
  ld64_osx-64        conda-forge/osx-64::ld64_osx-64-609-hfd63004_12
  libclang-cpp14     conda-forge/osx-64::libclang-cpp14-14.0.6-default_h55ffa42_0
  libcxx             conda-forge/osx-64::libcxx-15.0.7-h71dddab_0
  libiconv           conda-forge/osx-64::libiconv-1.17-hac89ed1_0
  ---- libllvm14 and 15!
  libllvm14          conda-forge/osx-64::libllvm14-14.0.6-h5b596cc_1
  libllvm15          conda-forge/osx-64::libllvm15-15.0.7-h7001e86_1
  ---
  libxml2            conda-forge/osx-64::libxml2-2.10.3-hb9e07b5_0
  libzlib            conda-forge/osx-64::libzlib-1.2.13-hfd90126_4
  llvm-tools         conda-forge/osx-64::llvm-tools-14.0.6-h5b596cc_1
  openssl            conda-forge/osx-64::openssl-3.1.0-hfd90126_0
  sigtool            conda-forge/osx-64::sigtool-0.1.3-h88f4db0_0
  tapi               conda-forge/osx-64::tapi-1100.0.11-h9ce4665_0
  xz                 conda-forge/osx-64::xz-5.2.6-h775f41a_0
  zstd               conda-forge/osx-64::zstd-1.5.2-hbc0c0cd_6
```
</details>

<details>
<summary>

```
conda-tree -p ~/conda-x86/envs/clang deptree
```

</summary>

```
$ conda-tree -p ~/conda-x86/envs/clang deptree
clangxx_osx-64==14.0.6
  ├─ clang_osx-64 14.0.6 [required: 14.0.6, h3113cd8_5]
  │  ├─ cctools_osx-64 973.0.1 [required: any]
  │  │  ├─ ld64_osx-64 609 [required: >=609,<610.0a0]
  │  │  │  ├─ libcxx 15.0.7 [required: any]
  │  │  │  ├─ libllvm14 14.0.6 [required: >=14.0.6,<14.1.0a0]
  │  │  │  │  ├─ libcxx 15.0.7 [required: >=14]
  │  │  │  │  └─ libzlib 1.2.13 [required: >=1.2.13,<1.3.0a0]
  │  │  │  ├─ sigtool 0.1.3 [required: any]
  │  │  │  │  └─ openssl 3.1.0 [required: >=3.0.0,<4.0a0]
  │  │  │  │     └─ ca-certificates 2022.12.7 [required: any]
  │  │  │  └─ tapi 1100.0.11 [required: >=1100.0.11,<1101.0a0]
  │  │  │     └─ libcxx 15.0.7 [required: >=10.0.0.a0]
  │  │  ├─ libcxx 15.0.7 [required: any]
  │  │  ├─ libllvm15 15.0.7 [required: >=15.0.7,<15.1.0a0]
  │  │  │  ├─ libcxx 15.0.7 [required: >=14]
  │  │  │  ├─ libxml2 2.10.3 [required: >=2.10.3,<2.11.0a0]
  │  │  │  │  ├─ icu 70.1 [required: >=70.1,<71.0a0]
  │  │  │  │  │  └─ libcxx 15.0.7 [required: >=12.0.1]
  │  │  │  │  ├─ libiconv 1.17 [required: >=1.17,<2.0a0]
  │  │  │  │  ├─ libzlib 1.2.13 [required: >=1.2.13,<1.3.0a0]
  │  │  │  │  └─ xz 5.2.6 [required: >=5.2.6,<6.0a0]
  │  │  │  ├─ libzlib 1.2.13 [required: >=1.2.13,<1.3.0a0]
  │  │  │  └─ zstd 1.5.2 [required: >=1.5.2,<1.6.0a0]
  │  │  │     ├─ libcxx 15.0.7 [required: >=14.0.6]
  │  │  │     └─ libzlib 1.2.13 [required: >=1.2.13,<1.3.0a0]
  │  │  ├─ libzlib 1.2.13 [required: >=1.2.13,<1.3.0a0]
  │  │  └─ sigtool 0.1.3 [required: any]
  │  │     └─ dependencies of sigtool displayed above
  │  ├─ clang 14.0.6 [required: 14.0.6.*]
  │  │  └─ clang-14 14.0.6 [required: 14.0.6, default_h55ffa42_0]
  │  │     ├─ libclang-cpp14 14.0.6 [required: 14.0.6, default_h55ffa42_0]
  │  │     │  ├─ libcxx 15.0.7 [required: >=13.0.1]
  │  │     │  └─ libllvm14 14.0.6 [required: >=14.0.6,<14.1.0a0]
  │  │     │     └─ dependencies of libllvm14 displayed above
  │  │     ├─ libcxx 15.0.7 [required: >=13.0.1]
  │  │     └─ libllvm14 14.0.6 [required: >=14.0.6,<14.1.0a0]
  │  │        └─ dependencies of libllvm14 displayed above
  │  ├─ compiler-rt 14.0.6 [required: 14.0.6.*]
  │  │  ├─ clang 14.0.6 [required: 14.0.6.*]
  │  │  │  └─ dependencies of clang displayed above
  │  │  ├─ clangxx 14.0.6 [required: 14.0.6.*]
  │  │  │  └─ clang 14.0.6 [required: 14.0.6, h694c41f_0]
  │  │  │     └─ dependencies of clang displayed above
  │  │  └─ compiler-rt_osx-64 14.0.6 [required: 14.0.6.*]
  │  │     ├─ clang 14.0.6 [required: 14.0.6.*]
  │  │     │  └─ dependencies of clang displayed above
  │  │     └─ clangxx 14.0.6 [required: 14.0.6.*]
  │  │        └─ dependencies of clangxx displayed above
  │  ├─ ld64_osx-64 609 [required: any]
  │  │  └─ dependencies of ld64_osx-64 displayed above
  │  └─ llvm-tools 14.0.6 [required: 14.0.6.*]
  │     ├─ libllvm14 14.0.6 [required: 14.0.6, h5b596cc_1]
  │     │  └─ dependencies of libllvm14 displayed above
  │     └─ libzlib 1.2.13 [required: >=1.2.13,<1.3.0a0]
  ├─ clangxx 14.0.6 [required: 14.0.6.*]
  │  └─ dependencies of clangxx displayed above
  ├─ libcxx 15.0.7 [required: >=14.0.6]
  └─ libllvm14 14.0.6 [required: >=14.0.6,<14.1.0a0]
     └─ dependencies of libllvm14 displayed above
```
</details>

**Pull request merged**
