### PR TITLE
update recipe

### PR DESCRIPTION
**Pull request by ocefpaf**
@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by ocefpaf** [comment]
@isuruf this is virtually the same recipe that @msarahan has on AnacondaRecipes but Windows is failing with different errors on each `vc` here :-/

**Comment by isuruf** [comment]
I don't see a 60.2 on anaconda.org, so maybe AnacondaRecipes is also not building. Btw, can you try upgrading to icu 62?

**Comment by ocefpaf** [comment]
> I don't see a 60.2 on anaconda.org, so maybe AnacondaRecipes is also not building. 

Aha. Thanks!

> Btw, can you try upgrading to icu 62?

Sure. Let me get the same version that exist no `defaults` first for compatibility.

**Comment by ocefpaf** [comment]
The recipe now is virtually the same as AnacondaRecipes but it is failing with:

```
cd /icu/lib/icu/58.2/..; \
    rm -f current && ln -s 58.2 current; \
    rm -f Makefile.inc && ln -s current/Makefile.inc Makefile.inc; \
    rm -f pkgdata.inc && ln -s current/pkgdata.inc pkgdata.inc
rm: cannot remove 'current': Is a directory
/bin/sh ./mkinstalldirs /icu/share/man/man1
/usr/bin/install -c -m 644 config/icu-config.1 /icu/share/man/man1
File not found - lib
0 File(s) copied
```

I'll try to spin a Windows machine to debug this.

**Comment by mariusvniekerk** [comment]
```
/usr/bin/install -c -m 644 ./config/mh-cygwin-msvc /icu/share/icu/58.2/config/mh-cygwin-msvc
/usr/bin/install -c ./mkinstalldirs /icu/share/icu/58.2/mkinstalldirs
/usr/bin/install -c ./install-sh /icu/share/icu/58.2/install-sh
/usr/bin/install -c -m 644 ./config/icu-uc.pc ./config/icu-i18n.pc ./config/icu-io.pc /icu/lib/pkgconfig/
/usr/bin/install -c -m 644 ./../LICENSE /icu/share/icu/58.2/LICENSE
/usr/bin/install -c ./config/icu-config /icu/bin/icu-config
/usr/bin/install -c -m 644 ./config/Makefile.inc /icu/lib/icu/58.2/Makefile.inc
/usr/bin/install -c -m 644 ./config/pkgdata.inc /icu/lib/icu/58.2/pkgdata.inc
```
This suggests that $PREFIX is not getting in there or is empty

**Pull request closed without merging**
